<?xml version="1.0"?>
<package format="3">
  <name>bot2</name>
  <version>0.0.1</version>
  <description>SLAM mapping task for TurtleBot3</description>

  <maintainer email="xianyun@todo.todo">xianyun</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <depend>rclpy</depend>
  <depend>geometry_msgs</depend>
  <depend>nav_msgs</depend>
  <depend>sensor_msgs</depend>

  <exec_depend>slam_toolbox</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
